.TH "Довідник каталогу Lab1/obj/Debug/net10.0" 3 "Звіт з Лаб3 ООП" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Довідник каталогу Lab1/obj/Debug/net10.0
.SH SYNOPSIS
.br
.PP
.SS "Файли"

.in +1c
.ti -1c
.RI "файл \fB\&.NETCoreApp,Version=v10\&.0\&.AssemblyAttributes\&.cs\fP"
.br
.ti -1c
.RI "файл \fBLab1\&.AssemblyInfo\&.cs\fP"
.br
.ti -1c
.RI "файл \fBLab1\&.GlobalUsings\&.g\&.cs\fP"
.br
.in -1c
