.TH "Console_Lab2.Vector" 3 "Звіт з Лаб3 ООП" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Console_Lab2.Vector \- Клас для роботи з одновимірним масивом \&.  

.SH SYNOPSIS
.br
.PP
.SS "Загальнодоступні елементи"

.in +1c
.ti -1c
.RI "void \fBGenerate\fP (int elementsLength)"
.br
.RI "Генерує елементи масиву випадковими числами\&. "
.ti -1c
.RI "void \fBShellSort\fP ()"
.br
.RI "Сортує масив за спаданням за алгоритмом Шелла\&. "
.ti -1c
.RI "int \fBSum\fP ()"
.br
.RI "Обчислює суму елементів масиву\&. "
.ti -1c
.RI "double \fBAverage\fP ()"
.br
.RI "Обчислює середнє арифметичне елементів масиву\&. "
.ti -1c
.RI "int \fBMax\fP (out int index)"
.br
.RI "Знаходить максимальний елемент масиву та його індекс\&. "
.ti -1c
.RI "int \fBCountOccurrences\fP (int value)"
.br
.RI "Визначає кількість повторень заданого елемента у масиві (лінійний пошук)\&. "
.in -1c
.SS "Властивості"

.in +1c
.ti -1c
.RI "int[] \fBElements\fP\fR [get]\fP"
.br
.RI "Елементи вектора\&. "
.in -1c
.SS "Приватні дані"

.in +1c
.ti -1c
.RI "int[] \fBelements\fP = new int[0]"
.br
.in -1c
.SH "Детальний опис"
.PP 
Клас для роботи з одновимірним масивом \&. 
.PP
Див\&. визначення в файлі \fBVector\&.cs\fP, рядок \fB7\fP
.SH "Опис методів компонент"
.PP 
.SS "double Console_Lab2\&.Vector\&.Average ()"

.PP
Обчислює середнє арифметичне елементів масиву\&. 
.PP
\fBПовертає\fP
.RS 4
Середнє арифметичне, заокруглене до 2 знаків\&.
.RE
.PP

.PP
Див\&. визначення в файлі \fBVector\&.cs\fP, рядок \fB78\fP
.SS "int Console_Lab2\&.Vector\&.CountOccurrences (int value)"

.PP
Визначає кількість повторень заданого елемента у масиві (лінійний пошук)\&. 
.PP
\fBАргументи\fP
.RS 4
\fIvalue\fP Значення для пошуку\&.
.RE
.PP
\fBПовертає\fP
.RS 4
Кількість знайдених повторень\&.
.RE
.PP

.PP
Див\&. визначення в файлі \fBVector\&.cs\fP, рядок \fB113\fP
.SS "void Console_Lab2\&.Vector\&.Generate (int elementsLength)"

.PP
Генерує елементи масиву випадковими числами\&. 
.PP
\fBАргументи\fP
.RS 4
\fIelementsLength\fP Кількість елементів для генерації\&.
.RE
.PP

.PP
Див\&. визначення в файлі \fBVector\&.cs\fP, рядок \fB21\fP
.SS "int Console_Lab2\&.Vector\&.Max (out int index)"

.PP
Знаходить максимальний елемент масиву та його індекс\&. 
.PP
\fBАргументи\fP
.RS 4
\fIindex\fP Індекс максимального елемента (або -1, якщо масив порожній)\&.
.RE
.PP
\fBПовертає\fP
.RS 4
Значення максимального елемента\&.
.RE
.PP

.PP
Див\&. визначення в файлі \fBVector\&.cs\fP, рядок \fB87\fP
.SS "void Console_Lab2\&.Vector\&.ShellSort ()"

.PP
Сортує масив за спаданням за алгоритмом Шелла\&. 
.PP
Див\&. визначення в файлі \fBVector\&.cs\fP, рядок \fB34\fP
.SS "int Console_Lab2\&.Vector\&.Sum ()"

.PP
Обчислює суму елементів масиву\&. 
.PP
\fBПовертає\fP
.RS 4
Сума елементів\&.
.RE
.PP

.PP
Див\&. визначення в файлі \fBVector\&.cs\fP, рядок \fB65\fP
.SH "Поля"
.PP 
.SS "int [] Console_Lab2\&.Vector\&.elements = new int[0]\fR [private]\fP"

.PP
Див\&. визначення в файлі \fBVector\&.cs\fP, рядок \fB10\fP
.SH "Повний список властивостей"
.PP 
.SS "int [] Console_Lab2\&.Vector\&.Elements\fR [get]\fP"

.PP
Елементи вектора\&. 
.PP
Див\&. визначення в файлі \fBVector\&.cs\fP, рядок \fB15\fP

.SH "Автор"
.PP 
Автоматично створено за допомогою Doxygen для Звіт з Лаб3 ООП з тексту програми\&.
