.TH "Console_Lab2.Program" 3 "Звіт з Лаб3 ООП" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Console_Lab2.Program \- Головний клас програми\&.  

.SH SYNOPSIS
.br
.PP
.SS "Приватні статичні елементи"

.in +1c
.ti -1c
.RI "static void \fBMain\fP ()"
.br
.RI "Точка входу, що запускає меню програми\&. "
.in -1c
.SH "Детальний опис"
.PP 
Головний клас програми\&. 
.PP
Див\&. визначення в файлі \fBProgram\&.cs\fP, рядок \fB8\fP
.SH "Опис методів компонент"
.PP 
.SS "void Console_Lab2\&.Program\&.Main ()\fR [static]\fP, \fR [private]\fP"

.PP
Точка входу, що запускає меню програми\&. 
.PP
Див\&. визначення в файлі \fBProgram\&.cs\fP, рядок \fB13\fP

.SH "Автор"
.PP 
Автоматично створено за допомогою Doxygen для Звіт з Лаб3 ООП з тексту програми\&.
