.TH "Console_Lab2.Matrix" 3 "Звіт з Лаб3 ООП" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Console_Lab2.Matrix \- Клас для роботи з матрицею (дані про зарплату співробітників за місяцями)\&.  

.SH SYNOPSIS
.br
.PP
.SS "Загальнодоступні елементи"

.in +1c
.ti -1c
.RI "void \fBGenerate\fP (int employees)"
.br
.RI "Генерує матрицю випадкових зарплат\&. "
.ti -1c
.RI "int \fBTotalSum\fP ()"
.br
.RI "Обчислює річний бюджет (загальну суму всіх виплат)\&. "
.ti -1c
.RI "int \fBMonthSalary\fP (int month)"
.br
.RI "Обчислює загальну зарплату всіх співробітників за вказаний місяць\&. "
.ti -1c
.RI "double \fBMonthAverageSalary\fP (int month)"
.br
.RI "Обчислює середню зарплату одного співробітника за вказаний місяць\&. "
.in -1c
.SS "Властивості"

.in +1c
.ti -1c
.RI "int[,] \fBData\fP\fR [get]\fP"
.br
.RI "Елементи матриці\&. "
.in -1c
.SS "Приватні дані"

.in +1c
.ti -1c
.RI "int \fBrows\fP"
.br
.ti -1c
.RI "int \fBcols\fP = \fBMONTH_COUNT\fP"
.br
.ti -1c
.RI "int[,] \fBdata\fP = null!"
.br
.in -1c
.SS "Приватні статичні дані"

.in +1c
.ti -1c
.RI "const int \fBMONTH_COUNT\fP = 12"
.br
.in -1c
.SH "Детальний опис"
.PP 
Клас для роботи з матрицею (дані про зарплату співробітників за місяцями)\&. 
.PP
Див\&. визначення в файлі \fBMatrix\&.cs\fP, рядок \fB7\fP
.SH "Опис методів компонент"
.PP 
.SS "void Console_Lab2\&.Matrix\&.Generate (int employees)"

.PP
Генерує матрицю випадкових зарплат\&. 
.PP
\fBАргументи\fP
.RS 4
\fIemployees\fP Кількість співробітників (рядків)\&.
.RE
.PP

.PP
Див\&. визначення в файлі \fBMatrix\&.cs\fP, рядок \fB23\fP
.SS "double Console_Lab2\&.Matrix\&.MonthAverageSalary (int month)"

.PP
Обчислює середню зарплату одного співробітника за вказаний місяць\&. 
.PP
\fBАргументи\fP
.RS 4
\fImonth\fP Номер місяця (1-12)\&.
.RE
.PP
\fBПовертає\fP
.RS 4
Середня місячна зарплата\&.
.RE
.PP

.PP
Див\&. визначення в файлі \fBMatrix\&.cs\fP, рядок \fB77\fP
.SS "int Console_Lab2\&.Matrix\&.MonthSalary (int month)"

.PP
Обчислює загальну зарплату всіх співробітників за вказаний місяць\&. 
.PP
\fBАргументи\fP
.RS 4
\fImonth\fP Номер місяця (1-12)\&.
.RE
.PP
\fBПовертає\fP
.RS 4
Загальна зарплата за місяць\&.
.RE
.PP

.PP
Див\&. визначення в файлі \fBMatrix\&.cs\fP, рядок \fB59\fP
.SS "int Console_Lab2\&.Matrix\&.TotalSum ()"

.PP
Обчислює річний бюджет (загальну суму всіх виплат)\&. 
.PP
\fBПовертає\fP
.RS 4
Сумарна зарплата всіх співробітників за всі місяці\&.
.RE
.PP

.PP
Див\&. визначення в файлі \fBMatrix\&.cs\fP, рядок \fB41\fP
.SH "Поля"
.PP 
.SS "int Console_Lab2\&.Matrix\&.cols = \fBMONTH_COUNT\fP\fR [private]\fP"

.PP
Див\&. визначення в файлі \fBMatrix\&.cs\fP, рядок \fB11\fP
.SS "int [,] Console_Lab2\&.Matrix\&.data = null!\fR [private]\fP"

.PP
Див\&. визначення в файлі \fBMatrix\&.cs\fP, рядок \fB12\fP
.SS "const int Console_Lab2\&.Matrix\&.MONTH_COUNT = 12\fR [static]\fP, \fR [private]\fP"

.PP
Див\&. визначення в файлі \fBMatrix\&.cs\fP, рядок \fB10\fP
.SS "int Console_Lab2\&.Matrix\&.rows\fR [private]\fP"

.PP
Див\&. визначення в файлі \fBMatrix\&.cs\fP, рядок \fB9\fP
.SH "Повний список властивостей"
.PP 
.SS "int [,] Console_Lab2\&.Matrix\&.Data\fR [get]\fP"

.PP
Елементи матриці\&. 
.PP
Див\&. визначення в файлі \fBMatrix\&.cs\fP, рядок \fB17\fP

.SH "Автор"
.PP 
Автоматично створено за допомогою Doxygen для Звіт з Лаб3 ООП з тексту програми\&.
