.TH "Lab2/Matrix.cs" 3 "Звіт з Лаб3 ООП" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Lab2/Matrix.cs
.SH SYNOPSIS
.br
.PP
.SS "Структури даних"

.in +1c
.ti -1c
.RI "class \fBConsole_Lab2\&.Matrix\fP"
.br
.RI "Клас для роботи з матрицею (дані про зарплату співробітників за місяцями)\&. "
.in -1c
.SS "Простори імен"

.in +1c
.ti -1c
.RI "namespace \fBConsole_Lab2\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматично створено за допомогою Doxygen для Звіт з Лаб3 ООП з тексту програми\&.
