.TH "Lab6/Program.cs" 3 "Звіт з Лаб3 ООП" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Lab6/Program.cs
.SH SYNOPSIS
.br
.PP
.SS "Функції"

.in +1c
.ti -1c
.RI "Console\&. \fBWriteLine\fP ('Hello, World!')"
.br
.in -1c
.SH "Опис функцій"
.PP 
.SS "Console\&. WriteLine (' Hello, World!' )"

.SH "Автор"
.PP 
Автоматично створено за допомогою Doxygen для Звіт з Лаб3 ООП з тексту програми\&.
