.TH "Lab2/obj/Debug/net10.0/.NETCoreApp,Version=v10.0.AssemblyAttributes.cs" 3 "Звіт з Лаб3 ООП" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Lab2/obj/Debug/net10.0/.NETCoreApp,Version=v10.0.AssemblyAttributes.cs
.SH SYNOPSIS
.br
.PP
.SH "Автор"
.PP 
Автоматично створено за допомогою Doxygen для Звіт з Лаб3 ООП з тексту програми\&.
