.TH "Console_Lab2.Vector" 3 "Звіт з Лаб3 ООП" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Console_Lab2.Vector
.SH SYNOPSIS
.br
.PP
.SS "Загальнодоступні елементи"

.in +1c
.ti -1c
.RI "void \fBGenerate\fP (int elementsLength)"
.br
.ti -1c
.RI "void \fBShellSort\fP ()"
.br
.ti -1c
.RI "int \fBSum\fP ()"
.br
.ti -1c
.RI "double \fBAverage\fP ()"
.br
.ti -1c
.RI "int \fBMax\fP ()"
.br
.ti -1c
.RI "int \fBCountOccurrences\fP (int value)"
.br
.in -1c
.SS "Властивості"

.in +1c
.ti -1c
.RI "int[] \fBElements\fP\fR [get]\fP"
.br
.in -1c
.SS "Приватні дані"

.in +1c
.ti -1c
.RI "int?[] \fBelements\fP"
.br
.in -1c
.SH "Детальний опис"
.PP 
Див\&. визначення в файлі \fBVector\&.cs\fP, рядок \fB4\fP
.SH "Опис методів компонент"
.PP 
.SS "double Console_Lab2\&.Vector\&.Average ()"

.PP
Див\&. визначення в файлі \fBVector\&.cs\fP, рядок \fB56\fP
.SS "int Console_Lab2\&.Vector\&.CountOccurrences (int value)"

.PP
Див\&. визначення в файлі \fBVector\&.cs\fP, рядок \fB70\fP
.SS "void Console_Lab2\&.Vector\&.Generate (int elementsLength)"

.PP
Див\&. визначення в файлі \fBVector\&.cs\fP, рядок \fB10\fP
.SS "int Console_Lab2\&.Vector\&.Max ()"

.PP
Див\&. визначення в файлі \fBVector\&.cs\fP, рядок \fB60\fP
.SS "void Console_Lab2\&.Vector\&.ShellSort ()"

.PP
Див\&. визначення в файлі \fBVector\&.cs\fP, рядок \fB20\fP
.SS "int Console_Lab2\&.Vector\&.Sum ()"

.PP
Див\&. визначення в файлі \fBVector\&.cs\fP, рядок \fB47\fP
.SH "Поля"
.PP 
.SS "int? [] Console_Lab2\&.Vector\&.elements\fR [private]\fP"

.PP
Див\&. визначення в файлі \fBVector\&.cs\fP, рядок \fB7\fP
.SH "Повний список властивостей"
.PP 
.SS "int [] Console_Lab2\&.Vector\&.Elements\fR [get]\fP"

.PP
Див\&. визначення в файлі \fBVector\&.cs\fP, рядок \fB9\fP

.SH "Автор"
.PP 
Автоматично створено за допомогою Doxygen для Звіт з Лаб3 ООП з тексту програми\&.
