.TH "Console_Lab2.Program" 3 "Звіт з Лаб3 ООП" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Console_Lab2.Program
.SH SYNOPSIS
.br
.PP
.SS "Приватні статичні елементи"

.in +1c
.ti -1c
.RI "static void \fBMain\fP ()"
.br
.in -1c
.SH "Детальний опис"
.PP 
Див\&. визначення в файлі \fBProgram\&.cs\fP, рядок \fB5\fP
.SH "Опис методів компонент"
.PP 
.SS "void Console_Lab2\&.Program\&.Main ()\fR [static]\fP, \fR [private]\fP"

.PP
Див\&. визначення в файлі \fBProgram\&.cs\fP, рядок \fB7\fP

.SH "Автор"
.PP 
Автоматично створено за допомогою Doxygen для Звіт з Лаб3 ООП з тексту програми\&.
