.TH "Console_Lab2.Matrix" 3 "Звіт з Лаб3 ООП" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Console_Lab2.Matrix
.SH SYNOPSIS
.br
.PP
.SS "Загальнодоступні елементи"

.in +1c
.ti -1c
.RI "void \fBGenerate\fP (int employees)"
.br
.ti -1c
.RI "int \fBTotalSum\fP ()"
.br
.ti -1c
.RI "int \fBMonthSalary\fP (int month)"
.br
.in -1c
.SS "Властивості"

.in +1c
.ti -1c
.RI "int[,] \fBData\fP\fR [get]\fP"
.br
.in -1c
.SS "Приватні дані"

.in +1c
.ti -1c
.RI "int \fBrows\fP"
.br
.ti -1c
.RI "int \fBcols\fP = 12"
.br
.ti -1c
.RI "int?[,] \fBdata\fP"
.br
.in -1c
.SH "Детальний опис"
.PP 
Див\&. визначення в файлі \fBMatrix\&.cs\fP, рядок \fB4\fP
.SH "Опис методів компонент"
.PP 
.SS "void Console_Lab2\&.Matrix\&.Generate (int employees)"

.PP
Див\&. визначення в файлі \fBMatrix\&.cs\fP, рядок \fB11\fP
.SS "int Console_Lab2\&.Matrix\&.MonthSalary (int month)"

.PP
Див\&. визначення в файлі \fBMatrix\&.cs\fP, рядок \fB36\fP
.SS "int Console_Lab2\&.Matrix\&.TotalSum ()"

.PP
Див\&. визначення в файлі \fBMatrix\&.cs\fP, рядок \fB24\fP
.SH "Поля"
.PP 
.SS "int Console_Lab2\&.Matrix\&.cols = 12\fR [private]\fP"

.PP
Див\&. визначення в файлі \fBMatrix\&.cs\fP, рядок \fB7\fP
.SS "int? [,] Console_Lab2\&.Matrix\&.data\fR [private]\fP"

.PP
Див\&. визначення в файлі \fBMatrix\&.cs\fP, рядок \fB8\fP
.SS "int Console_Lab2\&.Matrix\&.rows\fR [private]\fP"

.PP
Див\&. визначення в файлі \fBMatrix\&.cs\fP, рядок \fB6\fP
.SH "Повний список властивостей"
.PP 
.SS "int [,] Console_Lab2\&.Matrix\&.Data\fR [get]\fP"

.PP
Див\&. визначення в файлі \fBMatrix\&.cs\fP, рядок \fB9\fP

.SH "Автор"
.PP 
Автоматично створено за допомогою Doxygen для Звіт з Лаб3 ООП з тексту програми\&.
