.TH "Console_Lab2" 3 "Звіт з Лаб3 ООП" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Console_Lab2
.SH SYNOPSIS
.br
.PP
.SS "Структури даних"

.in +1c
.ti -1c
.RI "class \fBMatrix\fP"
.br
.ti -1c
.RI "class \fBProgram\fP"
.br
.ti -1c
.RI "class \fBService\fP"
.br
.ti -1c
.RI "class \fBVector\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматично створено за допомогою Doxygen для Звіт з Лаб3 ООП з тексту програми\&.
