.TH "Console_Lab2.Service" 3 "Звіт з Лаб3 ООП" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Console_Lab2.Service
.SH SYNOPSIS
.br
.PP
.SS "Загальнодоступні елементи"

.in +1c
.ti -1c
.RI "int \fBReadInt\fP (string message)"
.br
.ti -1c
.RI "void \fBPrintVector\fP (int[] data)"
.br
.ti -1c
.RI "void \fBPrintMatrix\fP (int[,] data)"
.br
.ti -1c
.RI "void \fBVectorBlock\fP (\fBVector\fP vector)"
.br
.ti -1c
.RI "void \fBMatrixBlock\fP (\fBMatrix\fP matrix)"
.br
.in -1c
.SH "Детальний опис"
.PP 
Див\&. визначення в файлі \fBService\&.cs\fP, рядок \fB6\fP
.SH "Опис методів компонент"
.PP 
.SS "void Console_Lab2\&.Service\&.MatrixBlock (\fBMatrix\fP matrix)"

.PP
Див\&. визначення в файлі \fBService\&.cs\fP, рядок \fB53\fP
.SS "void Console_Lab2\&.Service\&.PrintMatrix (int data[,])"

.PP
Див\&. визначення в файлі \fBService\&.cs\fP, рядок \fB22\fP
.SS "void Console_Lab2\&.Service\&.PrintVector (int[] data)"

.PP
Див\&. визначення в файлі \fBService\&.cs\fP, рядок \fB13\fP
.SS "int Console_Lab2\&.Service\&.ReadInt (string message)"

.PP
Див\&. визначення в файлі \fBService\&.cs\fP, рядок \fB8\fP
.SS "void Console_Lab2\&.Service\&.VectorBlock (\fBVector\fP vector)"

.PP
Див\&. визначення в файлі \fBService\&.cs\fP, рядок \fB34\fP

.SH "Автор"
.PP 
Автоматично створено за допомогою Doxygen для Звіт з Лаб3 ООП з тексту програми\&.
