.TH "lesson1.Program" 3 "Звіт з Лаб3 ООП" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lesson1.Program
.SH SYNOPSIS
.br
.PP
.SS "Приватні статичні елементи"

.in +1c
.ti -1c
.RI "static void \fBMain\fP ()"
.br
.ti -1c
.RI "static void \fBTask1\fP ()"
.br
.ti -1c
.RI "static void \fBTask2\fP ()"
.br
.ti -1c
.RI "static void \fBTask3\fP ()"
.br
.ti -1c
.RI "static void \fBTask4\fP ()"
.br
.ti -1c
.RI "static void \fBTask5\fP ()"
.br
.in -1c
.SH "Детальний опис"
.PP 
Див\&. визначення в файлі \fBProgram\&.cs\fP, рядок \fB5\fP
.SH "Опис методів компонент"
.PP 
.SS "void lesson1\&.Program\&.Main ()\fR [static]\fP, \fR [private]\fP"

.PP
Див\&. визначення в файлі \fBProgram\&.cs\fP, рядок \fB7\fP
.SS "void lesson1\&.Program\&.Task1 ()\fR [static]\fP, \fR [private]\fP"

.PP
Див\&. визначення в файлі \fBProgram\&.cs\fP, рядок \fB59\fP
.SS "void lesson1\&.Program\&.Task2 ()\fR [static]\fP, \fR [private]\fP"

.PP
Див\&. визначення в файлі \fBProgram\&.cs\fP, рядок \fB84\fP
.SS "void lesson1\&.Program\&.Task3 ()\fR [static]\fP, \fR [private]\fP"

.PP
Див\&. визначення в файлі \fBProgram\&.cs\fP, рядок \fB105\fP
.SS "void lesson1\&.Program\&.Task4 ()\fR [static]\fP, \fR [private]\fP"

.PP
Див\&. визначення в файлі \fBProgram\&.cs\fP, рядок \fB124\fP
.SS "void lesson1\&.Program\&.Task5 ()\fR [static]\fP, \fR [private]\fP"

.PP
Див\&. визначення в файлі \fBProgram\&.cs\fP, рядок \fB143\fP

.SH "Автор"
.PP 
Автоматично створено за допомогою Doxygen для Звіт з Лаб3 ООП з тексту програми\&.
